### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by ChikuwaJB** [antonreshetov/vue-eva-icons#2]
Hi

I tried to use this package.
But I got `This dependency was not found` error.

```
This dependency was not found: 
* vue-eva-icons in ./plugins/vue-eva-icons.js
```

I suspect that this package isn't contain build.

<img width="419" alt="2018-12-09 16 42 59" src="https://user-images.githubusercontent.com/13606256/49694670-9b79fd80-fbd1-11e8-9ea4-b41bc9a0de3c.png">
<img width="504" alt="2018-12-09 16 43 04" src="https://user-images.githubusercontent.com/13606256/49694671-9fa61b00-fbd1-11e8-9307-956efcd3fe0e.png">

**Comment by ChikuwaJB** [comment]
I created pull request #3

**Comment by antonreshetov** [comment]
Hello @ChikuwaJB

To use vue-eva-icons you must install via `npm i vue-eva-icons` in your project, not just download the repository. Аnd then follow the instructions https://github.com/antonreshetov/vue-eva-icons#install File demo.html is autogenerated by vue-cli and is not intended to be used.
